### ISSUE TITLE
cannot run with python3.5

### ISSUE THREAD

**Issue by heyPIAO** [zk4/m3u8_dl#2]
Traceback (most recent call last):
  File "/usr/local/bin/m3_dl", line 5, in <module>
    from m3_dl import entry_point
  File "/usr/local/lib/python3.5/dist-packages/m3_dl/__init__.py", line 1, in <module>
    from .m3_dl import (entry_point,
  File "/usr/local/lib/python3.5/dist-packages/m3_dl/m3_dl.py", line 80
    logger.debug(f'{s} found')
                            ^
SyntaxError: invalid syntax

what's the environment requirements of this tool? 
Thank you so much~

**Comment by zk4** [comment]
I update the pip package. You can try install it again. 
``` python
pip3 install -U m3_dl
```
If this error still exsit. Try bump your python env to 3.7.1
